import Blogs from "@/Components/HomePage/Blogs/Blogs";
import Fetured from "@/Components/HomePage/Fetured/Fetured";
import Hero from "@/Components/HomePage/Hero/Hero";
import Products from "@/Components/HomePage/Products/Products";
import Head from "next/head";

export default function Home() {
  return (
    <main className="">
      <Head>
        <title>Gym Friday</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="../assets/favicon/favicon.ico" />
      </Head>
      <Hero />
     <Blogs />
      <Products />
     {/*   <Fetured/> */}
    </main>
  );
}
{/* <ProgressBar state={progress}/> */}

        {/* {progress === 1 && (
          <>
            <MetaData state={state} progresState={ progress} dispatch={dispatch} setState={setprogress} />
          </>
        )} */}
        {/* {progress === 2 && (
          <>
            <TextEditor progresState={ progress} dispatch={dispatch}  setState={setprogress}/>
          </>
        )}
        {progress === 3 && (
          <>
            <UploadImage progresState={ progress} dispatch={dispatch}  setState={setprogress} />
          </>
        )}
        {progress === 4 && (
          <>
            <Preview progresState={ progress} setState={setprogress}/>
          </>
        )} */}