import Head from "next/head";
import image from '../Assets/gym-firiday-textandicon logo.png'
import Image from "next/image";
import Marquee from "react-fast-marquee";


export default function Home() {
  return (
    <main className="relative select-none h-screen overflow-hidden">
    <Head>
        <title>Gym Friday</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="../assets/favicon/favicon.ico" />
      </Head>
   
      <Image alt="" className="w-96 z-50 absolute top-0 left-0 right-0 bottom-0 m-auto" src={image}></Image>
      <Marquee>
        <h1 className="text-outline my-4 text-8xl text-zinc-200 font-bold">
          {" "}
          GYM FRIDAY IS COMING SOON
        </h1>
      </Marquee>
      <Marquee direction="right">
        <h1 className="text-outline my-4 text-8xl text-zinc-200 font-bold">
          {" "}
          GYM FRIDAY IS COMING SOON
        </h1>
      </Marquee>
      <Marquee>
        <h1 className="text-outline  my-4 text-8xl text-zinc-200 font-bold">
          {" "}
          GYM FRIDAY IS COMING SOON
        </h1>
      </Marquee>
      <Marquee direction="right">
        <h1 className="text-outline my-4 text-8xl text-zinc-200 font-bold">
          {" "}
          GYM FRIDAY IS COMING SOON
        </h1>
      </Marquee>
      <Marquee>
        <h1 className="text-outline my-4 text-8xl text-zinc-200 font-bold">
          {" "}
          GYM FRIDAY IS COMING SOON
        </h1>
      </Marquee>
      <Marquee direction="right">
        <h1 className="text-outline my-4 text-8xl text-zinc-200 font-bold">
          {" "}
          GYM FRIDAY IS COMING SOON
        </h1>
      </Marquee>
      <Marquee>
        <h1 className="text-outline my-4 text-8xl text-zinc-200 font-bold">
          {" "}
          GYM FRIDAY IS COMING SOON
        </h1>
      </Marquee>
      <Marquee direction="right">
        <h1 className="text-outline my-4 text-8xl text-zinc-200 font-bold">
          {" "}
          GYM FRIDAY IS COMING SOON
        </h1>
      </Marquee>
    </main>
  );
}
